# Generated by Django 4.1.7 on 2023-03-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminWorkspace', '0006_auto_20181103_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
