# Generated by Django 4.1.7 on 2023-03-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffWorkspace', '0006_auto_20181028_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='item_no',
            field=models.CharField(max_length=50),
        ),
    ]
